# bundle exec jekyll server --livereload

title: SharpeN's Blog
email: sharpenofficial@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This site is dedicated to technology, both new and old. Here I talk
  about my misadventures and how I (sometimes) manage to fix them.
baseurl: "" # the subpath of your site, e.g. /blog
url: "sharpenblog.github.io" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
github_username: andy0dvlpr

# Build settings
theme: minima
plugins:
  - jekyll-feed